<?php

namespace App\Models;

use System\Auth\Authenticatable;
use System\Model\BaseModel;

class User extends BaseModel implements Authenticatable
{
    /**
     * @var string Table in DB
     */
    protected $table = 'users';

    /**
     * @var string Which column is the username
     */
    protected $username = 'email';

    /**
     * @var array Validation rules
     */
    protected static $rules = [
        'required' => ['email', 'password', 'phone'],
        'email' => 'email',
        'lengthMin' => ['password', 5],
        'numeric' => 'phone'
    ];

    public static function validate(array $data)
    {
        parent::validate($data); // TODO: Change the autogenerated stub
    }
}